### ISSUE TITLE
Arithmetical-Logical parser

### ISSUE THREAD

**Issue by judovana** [gbenroscience/ParserNG#13]
hi!

I had started to look into ParserNG,  because it seemed to be best fit for  https://github.com/judovana/jenkins-report-generic-chart-column/commit/52421b0872ee647f8482c8afc84bc02349ce0234 (and few following commits)

I think the best would be to contribute the
 * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/main/java/hudson/plugins/report/genericchart/math/LogicalExpressionParser.java
 *  https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/main/java/hudson/plugins/report/genericchart/math/ComparingExpressionParser.java

I would return it back to your project moreover as its,  next to MathExpression as ArithmeticalLogicalExpression (so original code will not be alerted), where ArithmeticalLogicalExpression will enhance MathExpression with comparisons and bool algebra. My current implementation do not support brackets. TBH, I'm not super excited to add, but maybe you would be able to help. If I would be doing that, I guess I will be lazy, and will take different bracket then () :)

Before I invest time to do so, are you interested by this feature or do you rather incline to keep it in downstream project?

The tests are worthy to check i guess;
 * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/test/java/hudson/plugins/report/genericchart/math/ComparingExpressionParserTest.java
 * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/test/java/hudson/plugins/report/genericchart/math/LogicalExpressionParserTest.java

**Comment by gbenroscience** [comment]
I have a bit of a workload at the moment. So pardon me if I cant respond asap.

**Comment by judovana** [comment]
Thanks for heads up. No worries, I will not rush anything more.

**Comment by gbenroscience** [comment]
> hi!
> 
> I had started to look into ParserNG, because it seemed to be best fit for [judovana/jenkins-report-generic-chart-column@52421b0](https://github.com/judovana/jenkins-report-generic-chart-column/commit/52421b0872ee647f8482c8afc84bc02349ce0234) (and few following commits)
> 
> I think the best would be to contribute the
> 
> * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/main/java/hudson/plugins/report/genericchart/math/LogicalExpressionParser.java
> * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/main/java/hudson/plugins/report/genericchart/math/ComparingExpressionParser.java
> 
> I would return it back to your project moreover as its, next to MathExpression as ArithmeticalLogicalExpression (so original code will not be alerted), where ArithmeticalLogicalExpression will enhance MathExpression with comparisons and bool algebra. My current implementation do not support brackets. TBH, I'm not super excited to add, but maybe you would be able to help. If I would be doing that, I guess I will be lazy, and will take different bracket then () :)
> 
> Before I invest time to do so, are you interested by this feature or do you rather incline to keep it in downstream project?
> 
> The tests are worthy to check i guess;
> 
> * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/test/java/hudson/plugins/report/genericchart/math/ComparingExpressionParserTest.java
> * https://github.com/judovana/jenkins-report-generic-chart-column/blob/master/src/test/java/hudson/plugins/report/genericchart/math/LogicalExpressionParserTest.java

Sorry for the delay, yet again. Thanks for all you are doing, and your patience.
After giving it more thought, for code and functional consistency, I wont be able to merge the PR yet, till you are able to sort out the issue with supporting multiple brackets.
Do you see yourself being able to do this efficiently in the nearest future?

**Comment by gbenroscience** [comment]
This issue has been resolved.
