### ISSUE TITLE
I find it slow in multithreaded environment 

### ISSUE THREAD

**Issue by cena7** [gbenroscience/ParserNG#14]
Nice project!

When you run on a multi threaded environment , I get performance for `solve()` in 3 digit milliseconds and over time performance degrade to 4 digit milliseconds.
I am doing simple expression and as instructed I'm not creating the expression each time.
( using Java 11)
i would expect it to take nano seconds , am i wrong ? 

`static MathExpression expression = new MathExpression("a=0;b=0;sqrt(a-b)");`

Any help is appreciated.

**Comment by judovana** [comment]
See https://github.com/gbenroscience/ParserNG/issues/4#issuecomment-724046397 for more detailed measures.

**Comment by judovana** [comment]
I would not call it a bug. The library is very well readable and perfectly extend-able. Though performance was kept in mind, the used algorithms are as they are. I will look if I see some unnecessary or some missing synchronization, but doubt a bit.

**Comment by gbenroscience** [comment]
Thanks for responding @judovana.
Thanks for using the library @cena7 
Can you reproduce the issue as applicable to your context? let's see how we can test and see if anything can be done.

**Comment by gbenroscience** [comment]
Seeing as how there has been neither response nor activity here, I have to close this issue.
