### ISSUE TITLE
Deploy on maven central?

### ISSUE THREAD

**Issue by victornoel** [gbenroscience/ParserNG#3]
Hi,

is there some plans to deploy this library on maven central? Or is there another repository where it is available, such as jitpack.io?

**Comment by gbenroscience** [comment]
Hi @victornoel, how are you using this library, please?
In a desktop app? in a mobile app?

Thanks!

**Comment by gbenroscience** [comment]
Meanwhile check this out.
You can retrieve the android clone of this library by doing the below:

[](https://github.com/gbenroscience/ParserNG-android)
```Java
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
Also add to your app's build.gradle file, under your dependencies, add:
```Java
dependencies {
	        implementation 'com.github.gbenroscience:parserng-android:0.1.1'
		
	}
```

**Comment by victornoel** [comment]
@gbenroscience I'm using it as a typical maven dependency for server app. So I guess we can say desktop app.

I tried unsuccessfully using it with jitpack but didn't use the android artefact, that must by why it didn't work. I will try again and report back here :)

**Comment by victornoel** [comment]
@gbenroscience I'm not sure why but it didn't work, maven is telling me it can't download the artefact from jibpack.io :/ I followed the configuration here: https://jitpack.io/#gbenroscience/parserng-android/0.1.1

**Comment by victornoel** [comment]
Ah, I know why it didn't work, because `com.github.gbenroscience:parserng-android:0.1.1` does not provide a jar, only an aar: https://jitpack.io/com/github/gbenroscience/parserng-android/master-4354ddd23a-1/build.log.

I need to use it as a jar :)

**Comment by gbenroscience** [comment]
Let me know if you have resolved the issue, or not; so I can close this.

**Comment by victornoel** [comment]
@gbenroscience as I said above, I didn't no :) I need a jar and there are no jar deployed either to maven central or jitpack.io.

**Comment by gbenroscience** [comment]
@victornoel , so just to be clear, the gradle build works , but what you need is a jar dist, right?

**Comment by gbenroscience** [comment]
@victornoel, so I have changed the project structure(should have done that a while back) to make this a pure java library. The parserng-android repo will serve for android devs.

The jar which you seek is in the dist folder of this library.
Let me know if you have any more needs.

**Comment by gbenroscience** [comment]
Check Github issues now.
I have changed the repo structure and the repo now comes with the needed jar in the dist folder.https://github.com/gbenroscience/ParserNG/tree/master/dist

Regards,
    On Tuesday, September 22, 2020, 01:22:06 PM GMT+1, Victor Noël <notifications@github.com> wrote:  
 
 


@gbenroscience as I said above, I didn't no :) I need a jar and there are no jar deployed either to maven central or jitpack.io.

**Comment by victornoel** [comment]
@gbenroscience sorry for the misunderstanding but I just want to be able to add the dependency to maven/gradle without building the jar myself or downloading it manually from the repository.

The correct way to do things is:
- provide a grade way to build the repository
- let jibpack.io build it and serve it

This is how you did it for parserng-android, so it would be great if it was the case here too if possible :)

**Comment by gbenroscience** [comment]
Okay then.
I will look into it. A bit busy now, though

**Comment by victornoel** [comment]
@gbenroscience no worry, when you can is ok :) thanks again

**Comment by gbenroscience** [comment]
@victornoel , the library is now available on maven central.

The README will be updated accordingly.

**Comment by victornoel** [comment]
@gbenroscience I don't think it is on maven central, see https://search.maven.org/artifact/com.github.gbenroscience/parser-ng

But I believe that now it should be available via jetpack.io: https://jitpack.io/#gbenroscience/ParserNG, so using the following coordinates:

gradle: `com.github.gbenroscience:parserng:master-SNAPSHOT`
maven:
```xml
        <dependency>
            <groupId>com.github.gbenroscience</groupId>
            <artifactId>parserng</artifactId>
            <version>master-SNAPSHOT</version>
        </dependency>
```

If you want it to be available via the specific version number, you need to add a tag with the version number (exactly like you did in parserng-android I believe).
If you add the tag `0.1.0`, your artefact will be available via `com.github.gbenroscience:ParserNG:0.1.0` on jitpack.io :)

FYI deploying on maven central is a manual operation (or automatized via continuous integration) that you have to do yourself as a developer. But I don't think it is needed if it's available via jitpack.io anyway :)

**Comment by victornoel** [comment]
@gbenroscience so good news, I can use it as a normal dependency to my project, it's cool :)

Bad news: it's compiled for Java 12 while the latest LTS is Java 11 and the one I am using, so I cannot use it in practice.
I believe it would be best to use java 11 here: https://github.com/gbenroscience/ParserNG/blob/master/pom.xml#L115-L116

Also, for the record, it is bad practice to commit the target repository to git :)

Thanks again!!

**Comment by gbenroscience** [comment]
So it works now with maven central right?
That's cool.

I will see to your other complaints.
I am taking time off my other responsibilities to attend to this; so bear with me.

**Comment by gbenroscience** [comment]
> @gbenroscience I don't think it is on maven central, see https://search.maven.org/artifact/com.github.gbenroscience/parser-ng
> 
> But I believe that now it should be available via jetpack.io: https://jitpack.io/#gbenroscience/ParserNG, so using the following coordinates:
> 
> gradle: `com.github.gbenroscience:parserng:master-SNAPSHOT`
> maven:
> 
> ```
>         <dependency>
>             <groupId>com.github.gbenroscience</groupId>
>             <artifactId>parserng</artifactId>
>             <version>master-SNAPSHOT</version>
>         </dependency>
> ```
> 
> If you want it to be available via the specific version number, you need to add a tag with the version number (exactly like you did in parserng-android I believe).
> If you add the tag `0.1.0`, your artefact will be available via `com.github.gbenroscience:ParserNG:0.1.0` on jitpack.io :)
> 
> FYI deploying on maven central is a manual operation (or automatized via continuous integration) that you have to do yourself as a developer. But I don't think it is needed if it's available via jitpack.io anyway :)

I had done all this already as at when you posted this reply.
Thanks

**Comment by gbenroscience** [comment]
> @gbenroscience so good news, I can use it as a normal dependency to my project, it's cool :)
> 
> Bad news: it's compiled for Java 12 while the latest LTS is Java 11 and the one I am using, so I cannot use it in practice.
> I believe it would be best to use java 11 here: https://github.com/gbenroscience/ParserNG/blob/master/pom.xml#L115-L116
> 
> Also, for the record, it is bad practice to commit the target repository to git :)
> 
> Thanks again!!

Thanks a lot.
I have fixed this

**Comment by gbenroscience** [comment]
> So it works now with maven central right?
> That's cool.
> 
> I will see to your other complaints.
> I am taking time off my other responsibilities to attend to this; so bear with me.

It is now compiled for Java 11.
Let me know if there is any other thing.

**Comment by victornoel** [comment]
> So it works now with maven central right?

No, it works with jitpack.io. Maven central is the official repository (https://search.maven.org/) in case it's not clear what I am talking about :)

But yes, it works with Maven the tool (and also with gradle and other maven-compliant tools)

> It is now compiled for Java 11.

@gbenroscience actually, it's not, you need to change the values in the pom (here: https://github.com/gbenroscience/ParserNG/blob/master/pom.xml#L115-L116), and the compilation is done by jitpack.io automatically.

> I had done all this already as at when you posted this reply.

Are you sure? Because it's still not on maven central (https://search.maven.org/artifact/com.github.gbenroscience/parser-ng) and there are no tags in the repository (https://github.com/gbenroscience/ParserNG/tags)

**Comment by gbenroscience** [comment]
Really? are you using this?

        <dependency>
            <groupId>com.github.gbenroscience</groupId>
            <artifactId>parser-ng</artifactId>
            <version>0.1.0</version>
        </dependency>

**Comment by victornoel** [comment]
@gbenroscience yes, the link I gave above (https://search.maven.org/artifact/com.github.gbenroscience/parser-ng) shows you what is available on maven central for this groupId and artifactId.

Can I ask what command you did run to deploy it there?

**Comment by gbenroscience** [comment]
mvn -e clean deploy.

I already pushed to sonatype. 
The push was successful.

Sorry they have to activate the sync process since its a first time push to maven, I believe.
I have notified them on the issues ticket at https://issues.sonatype.org/

Thanks a lot

**Comment by victornoel** [comment]
@gbenroscience I better understand, glad you found the solution and thank you very much for your patience :)

I still think it would be better to setup the pom to be Java 11 compatible to ensure everybody can use it. Or even Java 8 maybe?

**Comment by gbenroscience** [comment]
Java 8? lol... I set it up to be Java 11 already anyway.
If the repo gets more users and we get more such requests, of course I will.
I would be able to settle down to correct any issues that might arise from the change, which I expect to be minimal anyway.

**Comment by gbenroscience** [comment]
Can you please comment here when you are able to see it on maven?
If I notice it first, I will do so and close the issue, also.

**Comment by victornoel** [comment]
haha :) 

> I set it up to be Java 11 already anyway.

but not in the pom which is in the repository:

https://github.com/gbenroscience/ParserNG/blob/a12f614ca2ad903da922fa47951917118491ed19/pom.xml#L115-L116

> Can you please comment here when you are able to see it on maven?
> If I notice it first, I will do so and close the issue, also.

Yes of course!

**Comment by gbenroscience** [comment]
> haha :)
> 
> > I set it up to be Java 11 already anyway.
> 
> but not in the pom which is in the repository:
> 
> https://github.com/gbenroscience/ParserNG/blob/a12f614ca2ad903da922fa47951917118491ed19/pom.xml#L115-L116
> 
> > Can you please comment here when you are able to see it on maven?
> > If I notice it first, I will do so and close the issue, also.
> 
> Yes of course!

Apologies. I didnt push after the change.

**Comment by gbenroscience** [comment]
Meanwhile in other good news, I set the compile target to 1.8, to see how much work would need to be done. Evidently, I used a lot of base language features at the time, so nothing broke.

I will push the changes, both to Git and Maven later on.

**Comment by gbenroscience** [comment]
So, it is finally available.

Please check: [here](https://search.maven.org/search?q=g:com.github.gbenroscience)

**Comment by victornoel** [comment]
@gbenroscience thank you, and also again thank you for your patience ^^
