### ISSUE TITLE
ParserNG fails to parse a simple math expression

### ISSUE THREAD

**Issue by victornoel** [gbenroscience/ParserNG#4]
Hi,

I may be missing something but I tried to write the following:
```java
MathExpression parserng = new MathExpression("x-x/y");
```

And I get the following error in the logs: `DETECTED ERROR! IN [(, x, -, x, /, y, )]`

I'm not sure what I am doing wrong :)

**Comment by gbenroscience** [comment]
Hi, Victor!

What are you trying to do exactly?

1. Create a function?
2. Evaluate an expression?

If 1.

To create a function in x and y, do:

        MathExpression parserng = new MathExpression("f(x,y) = x-x/y; f(2,3);");
        System.out.println("res:  "+parserng.solve());

If 2.

You need to initialize the variables x and y.

e.g: 

        MathExpression parserng = new MathExpression("x=2;y=1;x-x/y");
        System.out.println("SEE???????\n"+parserng.solve());

**Comment by victornoel** [comment]
@gbenroscience ah indeed, the exact thing I'm doing is:
```java
MathExpression parserng = new MathExpression("x-x/y");

public double parserng() {
        parserng.setValue("x", String.valueOf(random.nextDouble() * 100));
        parserng.setValue("y", String.valueOf(1 + random.nextDouble() * 100));
        return Double.parseDouble(parserng.solve());
}
```

and the method `parserng()` is called repeatedly (I am writing a benchmark to compare many math parsing libraries).

So I should have wrote `new MathExpression("x=0;y=0;x-x/y");` I suppose

**Comment by gbenroscience** [comment]
To create a function, you may also do:


        FunctionManager.add("f(x,y) = x-x/y");
        Function f = FunctionManager.lookUp("f");
        
        System.out.println(f.calc(2,3));

The library represents functions in 2 ways:

        1. f(x,y,z,...) = expr_in_said_variables
        2. f = @(x,y,z)expr_in_said_variables.

So you may do:

        
        f(x,y) = x - x/y
Or 

        f = @(x,y)x-x/y

**Comment by victornoel** [comment]
ah, I like the `Function`-based version!

**Comment by gbenroscience** [comment]
> @gbenroscience ah indeed, the exact thing I'm doing is:
> 
> ```java
> MathExpression parserng = new MathExpression("x-x/y");
> 
> public double parserng() {
>         parserng.setValue("x", String.valueOf(random.nextDouble() * 100));
>         parserng.setValue("y", String.valueOf(1 + random.nextDouble() * 100));
>         return Double.parseDouble(parserng.solve());
> }
> ```
> 
> and the method `parserng()` is called repeatedly (I am writing a benchmark to compare many math parsing libraries).
> 
> So I should have wrote `new MathExpression("x=0;y=0;x-x/y");` I suppose

True, but if you initialize y to zero, your expression is going to throw an error, so maybe use 1 and 1 or something like that

**Comment by gbenroscience** [comment]
> ah, I like the `Function`-based version!

True! and I can see why, too. I had to roll this out back then for convenience in plotting graphs and doing various iterations.

**Comment by gbenroscience** [comment]
Something like this could help:

  FunctionManager.add("f(x,y) = x-x/y");
        Function fxy = FunctionManager.lookUp("f");
         
        double iterations = 100;

        for(int i=0;i<iterations;i++){
            fxy.calc(2,3);//or some dynamic value
        }

**Comment by victornoel** [comment]
I even did this (to avoid using global static state):
```java
    private parser.Function parserng = new parser.Function("f(x,y) = x-x/y");

    @Benchmark
    public double parserng() {
        return parserng.calc(
            random.nextDouble() * 100,
            1 + random.nextDouble() * 100
        );
    }
```

Would you be interested in the benchmark results?

**Comment by gbenroscience** [comment]
Functions can also handle matrices,... just saying.

Do:

    
        FunctionManager.add("M=@(3,3)(3,4,1,2,4,7,9,1,-2)");
        Function matrixFunction = FunctionManager.lookUp("M");
       
        System.out.println("determinant: "+matrixFunction.calcDet());
        
And you can work with the underlying matrix by doing:
 
        Matrix matrix = matrixFunction.getMatrix();
        
        System.out.println("underlying matrix: "+matrix);

**Comment by gbenroscience** [comment]
> I even did this (to avoid using global static state):
> 
> ```java
>     private parser.Function parserng = new parser.Function("f(x,y) = x-x/y");
> 
>     @Benchmark
>     public double parserng() {
>         return parserng.calc(
>             random.nextDouble() * 100,
>             1 + random.nextDouble() * 100
>         );
>     }
> ```
> 
> Would you be interested in the benchmark results?

If you would be so generous, I would be interested

**Comment by victornoel** [comment]
@gbenroscience ok, I will open another issue when it is ready :)

Let me close this now that all is good here!

**Comment by gbenroscience** [comment]
> I even did this (to avoid using global static state):
> 
> ```java
>     private parser.Function parserng = new parser.Function("f(x,y) = x-x/y");
> 
>     @Benchmark
>     public double parserng() {
>         return parserng.calc(
>             random.nextDouble() * 100,
>             1 + random.nextDouble() * 100
>         );
>     }
> ```
> 
> Would you be interested in the benchmark results?


@victornoel , unfortunately I didn't hear from you about the benchmark results again.

Thanks

**Comment by victornoel** [comment]
@gbenroscience yep, sorry, it's finally available: https://github.com/victornoel/math-formula-parsers-benchmark :)

**Comment by gbenroscience** [comment]
Oh okay, thanks. Good to see it didn't fail any of your tests.

Looks a bit slow on execution though.
I will take a look at possible optimisations.

Thanks

**Comment by gbenroscience** [comment]
@victornoel would like to see the updated results for your benchmarks in 2026.
If you decide to do this, you may use version 1.1.4 or whatever version is the latest when you do it.
ParserNG now runs on both standard mode and turbo mode.
Let me know if you need help

**Comment by victornoel** [comment]
Hey @gbenroscience, I'm a bit under the water, but it should be quite easy for you to run them and if you want to submit a PR so that we update the repository with the latest numbers?
