### ISSUE TITLE
Instructions in readme.md

### ISSUE THREAD

**Issue by deepfriedoreos** [gbenroscience/ParserNG#7]
The README.md file states:

MathExpression expression = new MathExpression("x^2+5*x+1");
for(int i=0; i<100000; i++){
expression.setValue("x", String.valueOf(i) );
expression.solve();//Use the value from here according to your iterative needs...e.g plot a graph , do some summation etc..
}

However, running this code results in the expression.solve() returning a syntax error each time.

In order to get it to work, I had to set the expression first with x=0;x^2+5*x+1.  Notice the initialization of x=0 in the expression.  MathExpression expression = new MathExpression("x=0;x^2+5*x+1");

Then, it worked just fine.

If the intention is to  not  require initialization before a loop, please correct MathExpression code.  If the intention is to keep it the way it is, please update your instructions to include the fact that the expression needs to be initialized.

Excellent work, by the way!!

**Comment by gbenroscience** [comment]
Hi @deepfriedoreos! 
Thanks for the feedback. I actually sorted this out for one of the previous issues closed.
I will update the README
