### ISSUE TITLE
not playing nicely with java module system?

### ISSUE THREAD

**Issue by joshualibrarian** [gbenroscience/ParserNG#8]
Hi there, I'm trying to use your library, but can't get it to resolve, despite being included fine in the `build.gradle`, I can't see any of the classes.  I suspect it's something to do with the new java module system, where it needs a `requires` line in my `module-info.java` file, but it can't be resolved there either.  When I look around, it seems you have odd ("math") package names, could that have to do with it, or is there something else going on?  Any ideas?  :)

**Comment by gbenroscience** [comment]
Hi @joshualibrarian,
Its good to know you want to use this library.
How are you using it?
In an Android project? or perhaps a Java desktop app? or some other usage? thanks.

**Comment by gbenroscience** [comment]
Due to inactivity on this issue and no response from the creator, I will be closing it now.
Thanks
