### ISSUE TITLE
Decimal part looks strange

### ISSUE THREAD

**Issue by EzSoftware2015** [gbenroscience/ParserNG#9]
A simple calculation: 
`6249.8+7522.1+7881.7+4339.5`

Returns the following result:
`25993.100000000002`

But expected:
`25993.1`

**Comment by gbenroscience** [comment]
Hi @EzSoftware2015. Thanks for using ParserNG.
What you are observing would be rounding errors. It has nothing to do with the parser's operation, but everything to do with how numbers work.

If you have any specific ideas, you may implement this at the level of your software, though.
Thanks again.
